# Generated by Django 3.2 on 2023-04-21 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230421_0947'),
        ('reviews', '0002_auto_20230421_1021'),
    ]

    operations = [
    ]
